# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
          matrix:
            node_version: [14.x]
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm i
      - name: Run builds
        run: npm run build --if-present
      - name: Run tests
        run: npm test
      - name: Archive data
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: List files
        run: ls
      # - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "varungarg455-ci-cd" #Must be unique in Heroku
      #     heroku_email: "varungarg455@gmail.com"
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "build"
          target: "./"